baseURL = "https://fasia.github.io"
title = "F.S."
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2024, Faezeh Siavashi"
ignoreErrors = ["error-missing-instagram-accesstoken"]

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "education"
    name = "Education"
    title = "Education"
    url = "/education/"
    weight = -100
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    title = "Publications"
    url = "/publications/"
    weight = -90
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -80
  [[menu.main]]
    identifier = "achievements"
    name = "Achievements"
    title = "Achievements"
    url = "/achievements/"
    weight = -70

# Configuration Features
[params]
  description = "Postdoctoral Researcher | McMaster University | HU | Hamilton, CA"      # Site meta data
  header_title = "Faezeh Siavashi, Ph.D."      # Header title
  header_subtitle = "Postdoctoral Researcher | McMaster University | Hamilton, CA" # Header subtitle
  home_image = "/images/avatar.png"          # Avatar in static dir.
  recent_posts = 3                         # Max no. of recent posts
  mainSections = ["posts", "post"]   # Main sections to include in recent posts
  [params.plugins]
  [[params.plugins.css]]
    URL = "css/academicons/css/academicons.css"
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontFamilyBase = "'Ubuntu Mono', serif" 
    fontColor = "#8C1515"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    # fa_icon = "fe fe-github"
    href = "http://github.com/fasia"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    # fa_icon = "fe fe-linkedin"
    href = "https://linkedin.com/in/faezeh-siavashi"
  [[params.social]]
    #fa_icon = "ai ai-2x ai-google-scholar"
    fa_icon = "ai ai-2x ai-google-scholar"
    href = "https://scholar.google.com/citations?hl=en&user=3LmJakUAAAAJ"
  [[params.social]]
    fa_icon = "fa fa-envelope fa-1x"
    href = "mailto:siavashf@mcmaster.ca"
